### ISSUE TITLE
plot of cases versus time

### ISSUE THREAD

**Issue by mtmorgan** [hubentu/COVID19Erie#1]
Would be great to have an additional panel showing increase (for now!) in number of cases as a function of time, maybe on a log scale.

**Comment by hubentu** [comment]
Hi @mtmorgan , thanks for the suggestion. I updated the daily cumulative cases
 plot and added a new count table to show all the counts including new increased numbers.
Best,
Qiang

**Comment by mtmorgan** [comment]
Looks great, thanks! any chance to toggle the y axis to be on a log scale?

**Comment by hubentu** [comment]
Sure. A button has been added to toggle the log scale. Please have a try. Thx.

**Comment by mtmorgan** [comment]
Nice, thanks!
